<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" ignored="0" total="4" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="29857" started-at="2022-01-10T12:38:45 IST" finished-at="2022-01-10T12:39:15 IST">
    <groups>
    </groups>
    <test name="Test3" duration-ms="19880" started-at="2022-01-10T12:38:45 IST" finished-at="2022-01-10T12:39:05 IST">
      <class name="EndtoEndFrameWork.validateNavigationBar">
        <test-method status="PASS" signature="intialize()[pri:0, instance:EndtoEndFrameWork.validateNavigationBar@304bb45b]" name="intialize" is-config="true" duration-ms="17443" started-at="2022-01-10T12:38:45 IST" finished-at="2022-01-10T12:39:03 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- intialize -->
        <test-method status="FAIL" signature="ValidateNavigationBar()[pri:0, instance:EndtoEndFrameWork.validateNavigationBar@304bb45b]" name="ValidateNavigationBar" duration-ms="217" started-at="2022-01-10T12:39:03 IST" finished-at="2022-01-10T12:39:03 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertFalse(Assert.java:67)
at org.testng.Assert.assertFalse(Assert.java:77)
at EndtoEndFrameWork.validateNavigationBar.ValidateNavigationBar(validateNavigationBar.java:40)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ValidateNavigationBar -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:EndtoEndFrameWork.validateNavigationBar@304bb45b]" name="tearDown" is-config="true" duration-ms="115" started-at="2022-01-10T12:39:05 IST" finished-at="2022-01-10T12:39:05 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- EndtoEndFrameWork.validateNavigationBar -->
    </test> <!-- Test3 -->
    <test name="Test2" duration-ms="20207" started-at="2022-01-10T12:38:45 IST" finished-at="2022-01-10T12:39:06 IST">
      <class name="EndtoEndFrameWork.validateTitleTest">
        <test-method status="PASS" signature="intialize()[pri:0, instance:EndtoEndFrameWork.validateTitleTest@35841320]" name="intialize" is-config="true" duration-ms="19870" started-at="2022-01-10T12:38:45 IST" finished-at="2022-01-10T12:39:05 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- intialize -->
        <test-method status="PASS" signature="ValidateTitle()[pri:0, instance:EndtoEndFrameWork.validateTitleTest@35841320]" name="ValidateTitle" duration-ms="170" started-at="2022-01-10T12:39:05 IST" finished-at="2022-01-10T12:39:06 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ValidateTitle -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:EndtoEndFrameWork.validateTitleTest@35841320]" name="tearDown" is-config="true" duration-ms="159" started-at="2022-01-10T12:39:06 IST" finished-at="2022-01-10T12:39:06 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- EndtoEndFrameWork.validateTitleTest -->
    </test> <!-- Test2 -->
    <test name="Test1" duration-ms="29857" started-at="2022-01-10T12:38:45 IST" finished-at="2022-01-10T12:39:15 IST">
      <class name="EndtoEndFrameWork.qaClickTest">
        <test-method status="FAIL" signature="NavigatePage(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:EndtoEndFrameWork.qaClickTest@1349883]" name="NavigatePage" duration-ms="20059" started-at="2022-01-10T12:38:46 IST" data-provider="getData" finished-at="2022-01-10T12:39:06 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[singhpritam007]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[lion007007]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[For restricted User]]>
              </value>
            </param>
          </params>
          <exception class="java.sql.SQLException">
            <message>
              <![CDATA[No suitable driver found for jdbc:mysql://localhost:3306/automation]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.sql.SQLException: No suitable driver found for jdbc:mysql://localhost:3306/automation
at java.sql.DriverManager.getConnection(DriverManager.java:689)
at java.sql.DriverManager.getConnection(DriverManager.java:247)
at resources.Base.getMySqlData(Base.java:73)
at EndtoEndFrameWork.qaClickTest.NavigatePage(qaClickTest.java:43)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.sql.SQLException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- NavigatePage -->
        <test-method status="FAIL" signature="NavigatePage(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:EndtoEndFrameWork.qaClickTest@1349883]" name="NavigatePage" duration-ms="8792" started-at="2022-01-10T12:39:06 IST" data-provider="getData" finished-at="2022-01-10T12:39:15 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[pritamsingh007]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[elephant008]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[For Valid User]]>
              </value>
            </param>
          </params>
          <exception class="java.sql.SQLException">
            <message>
              <![CDATA[No suitable driver found for jdbc:mysql://localhost:3306/automation]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.sql.SQLException: No suitable driver found for jdbc:mysql://localhost:3306/automation
at java.sql.DriverManager.getConnection(DriverManager.java:689)
at java.sql.DriverManager.getConnection(DriverManager.java:247)
at resources.Base.getMySqlData(Base.java:73)
at EndtoEndFrameWork.qaClickTest.NavigatePage(qaClickTest.java:43)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.sql.SQLException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- NavigatePage -->
      </class> <!-- EndtoEndFrameWork.qaClickTest -->
    </test> <!-- Test1 -->
  </suite> <!-- Suite -->
</testng-results>
